global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'distributed-job-scheduler'

scrape_configs:
  - job_name: 'scheduler-nodes'
    static_configs:
      - targets:
        - 'scheduler1:8001'
        - 'scheduler2:8002'
        - 'scheduler3:8003'
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
